
print "#######                   #######"
print " #     #      ####         #     #"
print " #      #    #    #        #      #"
print " #      #    #    #        #      #"
print " #      #     #  #         #      #"
print " #      #      ##          #      #"
print " #      #     #  #         #      #"
print " #      #    #    # #      #      #" 
print " #      #    #     ##      #      #"
print " #      #    #      #      #      #"
print " #     #     #     # #     #     #"
print "#######       #####   #   #######"
print "          THE REVENGENCE"
