function displayTitle()
	print "#######                   #######"
	print " #     #      ####         #     #"
	print " #      #    #    #        #      #"
	print " #      #    #    #        #      #"
	print " #      #     #  #         #      #"
	print " #      #      ##          #      #"
	print " #      #     #  #         #      #"
	print " #      #    #    # #      #      #" 
	print " #      #    #     ##      #      #"
	print " #      #    #      #      #      #"
	print " #     #     #     # #     #     #"
	print "#######       #####   #   #######"
	print "          THE REVENGENCE"
end
